<?php echo $this->extend('Back/Layout/main'); ?>
<?php echo $this->section('title'); ?>Comissões<?php echo $this->endSection(); ?>
<?php echo $this->section('content'); ?>
<div class="container-fluid">
<div class="card shadow mb-4"><div class="card-header"><h6>Atendimentos para confirmar</h6><span><?php echo date('d/m/Y', strtotime($weekStart)); ?> a <?php echo date('d/m/Y', strtotime($weekEnd)); ?></span></div><div class="card-body">
<?php if (empty($pendingSchedules)): ?><p class="text-muted">Nenhum atendimento pendente de confirmação nesta semana.</p><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Data</th><th>Cliente</th><th>Serviço</th><th>Unidade</th><th>Profissional</th><th>Valores</th><th>Ação</th></tr></thead><tbody>
<?php foreach ($pendingSchedules as $schedule): ?><tr><td><?php echo date('d/m/Y H:i', strtotime($schedule->chosen_date)); ?></td><td><?php echo esc($schedule->customer_name ?: 'Cliente cadastrado'); ?><br><small><?php echo esc($schedule->customer_phone); ?></small></td><td><?php echo esc($schedule->service); ?></td><td><?php echo esc($schedule->unit); ?></td><td><?php echo esc($schedule->professional ?: 'Não definido'); ?></td><td colspan="2"><?php echo form_open(route_to('super.schedules.confirm', $schedule->id)); ?><?php foreach ($pendingServices[$schedule->id] as $service): ?><div class="form-row mb-2"><div class="col"><label class="small mb-1"><?php echo esc($service['name']); ?></label><input type="number" name="service_amount[<?php echo (int) $service['service_id']; ?>]" min="0" step="0.01" class="form-control form-control-sm" placeholder="Valor" required></div><div class="col"><label class="small mb-1">Comissão (%)</label><input type="number" name="commission_percentage[<?php echo (int) $service['service_id']; ?>]" min="0" max="100" step="0.01" class="form-control form-control-sm" placeholder="%" required></div></div><?php endforeach; ?><button class="btn btn-sm btn-primary" type="submit">Confirmar atendimento</button><?php echo form_close(); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</div></div>
<div class="card shadow mb-4"><div class="card-header"><h6>Comissões da semana</h6><span>Atendimentos confirmados</span></div><div class="card-body">
<?php if (empty($rows)): ?><p class="text-muted">Nenhum atendimento confirmado nesta semana.</p><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>Profissional</th><th>Atendimentos</th><th>Total</th><th>Situação</th><th>Ação</th></tr></thead><tbody>
<?php foreach ($rows as $row): $settlement = $paid[$row->professional_id] ?? null; ?><tr><td><?php echo esc($row->professional); ?></td><td><?php echo (int) $row->appointments; ?></td><td>R$ <?php echo number_format((float) $row->total, 2, ',', '.'); ?></td><td><?php echo $settlement ? 'Pago em ' . date('d/m/Y H:i', strtotime($settlement['paid_at'])) : 'Pendente'; ?></td><td><?php if (!$settlement): ?><?php echo form_open(route_to('commissions.pay', $row->professional_id)); ?><button class="btn btn-sm btn-primary" type="submit">Marcar como pago</button><?php echo form_close(); ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
</div></div></div>
</div></div></div>
<?php echo $this->endSection(); ?>
